import { spawn, type ChildProcess } from "node:child_process";
import { existsSync } from "node:fs";
import { access, appendFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import { createInterface } from "node:readline";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import type { Logger } from "pino";
import type { AppConfig } from "../config.js";
import type { RepoRow } from "../db/types.js";
import { spawnCollect } from "../utils/spawnCollect.js";
import { buildRepoCheckoutPath } from "./gitWorkspaceService.js";

const GENERATED_HEADER = "# Generated by Actuarius. Do not commit; this file routes repo memory to MemPalace.";
const DEFAULT_ROOMS = [
  { name: "src", keywords: ["src", "source", "code", "implementation"] },
  { name: "tests", keywords: ["test", "tests", "spec", "fixture"] },
  { name: "docs", keywords: ["doc", "docs", "readme", "guide"] },
  { name: "configuration", keywords: ["config", "docker", "deploy", "infra", "terraform"] },
  { name: "general", keywords: [] }
] as const;

export interface RepoMemoryIdentity {
  owner: string;
  repo: string;
  fullName: string;
}

/**
 * Thrown for deterministic startup failures that a retry cannot fix (a
 * missing binary, a malformed existing project config) — as opposed to the
 * federation server failing its health check, which can be transient. Callers
 * (see memPalaceRemoteStartup.ts) use this to skip retrying.
 */
export class MemPalaceRemoteConfigError extends Error {
  public constructor(message: string) {
    super(message);
    this.name = "MemPalaceRemoteConfigError";
  }
}

export interface MemPalaceRemoteServiceOptions {
  homeDir?: string;
}

interface TokenEntry {
  token?: unknown;
  name?: unknown;
  enabled?: unknown;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function findProjectConfigPath(dir: string): Promise<string | null> {
  const primaryPath = join(dir, "mempalace.yaml");
  if (await pathExists(primaryPath)) return primaryPath;
  const legacyPath = join(dir, "mempal.yaml");
  if (await pathExists(legacyPath)) return legacyPath;
  return null;
}

function sanitizeWingPart(value: string): string {
  const normalized = value.trim().toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  return normalized || "repo";
}

export function buildRepoMemoryWing(repo: RepoMemoryIdentity): string {
  // Mirrors `mempalace-cli init` naming (wing_<directory-name>) so repo wings
  // merge by name with palaces initialised locally under MemPalace federation.
  // Repos with identical names but different owners would share a wing; a
  // single-guild deployment connects few repos, so this is accepted.
  return "wing_" + sanitizeWingPart(repo.repo);
}

export function parseProjectConfigWing(configText: string): string | null {
  for (const rawLine of configText.split(/\r?\n/u)) {
    const line = rawLine.trim();
    const match = /^wing\s*:\s*["']?([^"'#\s]+)["']?\s*(?:#.*)?$/u.exec(line);
    if (match?.[1]) return match[1];
  }
  return null;
}

function renderGeneratedProjectConfig(wing: string, remoteName: string): string {
  const lines = [
    GENERATED_HEADER,
    "wing: " + wing,
    "routing:",
    "  mode: combined",
    "  remote: " + remoteName,
    "  write: remote",
    "rooms:"
  ];
  for (const room of DEFAULT_ROOMS) {
    lines.push("  - name: " + room.name);
    lines.push(room.keywords.length > 0 ? "    keywords: [" + room.keywords.join(", ") + "]" : "    keywords: []");
  }
  return lines.join("\n") + "\n";
}

function uniqueRepos(rows: RepoRow[]): RepoMemoryIdentity[] {
  const seen = new Set<string>();
  const repos: RepoMemoryIdentity[] = [];
  for (const row of rows) {
    const key = row.full_name.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    repos.push({ owner: row.owner, repo: row.repo, fullName: row.full_name });
  }
  return repos;
}

async function readJsonObject(path: string): Promise<Record<string, unknown>> {
  if (!(await pathExists(path))) return {};
  try {
    const parsed = JSON.parse(await readFile(path, "utf8")) as unknown;
    return isRecord(parsed) ? parsed : {};
  } catch {
    return {};
  }
}

async function readTokenEntries(path: string): Promise<TokenEntry[]> {
  if (!(await pathExists(path))) return [];
  try {
    const parsed = JSON.parse(await readFile(path, "utf8")) as unknown;
    return Array.isArray(parsed) ? parsed.filter(isRecord) : [];
  } catch {
    return [];
  }
}

export class MemPalaceRemoteService {
  private readonly config: AppConfig;
  private readonly logger: Logger;
  private readonly homeDir: string;
  private readonly repoCheckouts = new Map<string, string>();
  private readonly repoWings = new Map<string, string>();
  private readonly mineJobs = new Map<string, Promise<void>>();
  private readonly projectConfigOps = new Map<string, Promise<string>>();
  private static readonly SERVER_RETRY_DELAY_MS = 30_000;
  private server: ChildProcess | null = null;
  private serverRunning = false;
  private serverDesired = false;
  private serverOp: Promise<void> = Promise.resolve();
  private serverRetryTimer: ReturnType<typeof setTimeout> | null = null;
  private expectedServerExit = false;
  private remoteToken: string | null = null;
  private tokenPromise: Promise<string> | null = null;
  private writeConfigPromise: Promise<void> = Promise.resolve();

  public constructor(config: AppConfig, logger: Logger, options: MemPalaceRemoteServiceOptions = {}) {
    this.config = config;
    this.logger = logger;
    this.homeDir = options.homeDir ?? homedir();
  }

  public async start(existingRepos: RepoRow[] = []): Promise<void> {
    if (!this.config.mempalaceRemoteEnabled) return;
    if (!existsSync(this.config.mempalaceCliPath)) {
      throw new MemPalaceRemoteConfigError("mempalace-cli binary not found at " + this.config.mempalaceCliPath);
    }
    await this.ensureToken();
    await this.configureKnownRepositories(existingRepos);
    await this.writeGlobalConfig();
    this.serverDesired = true;
    await this.bringServerUp();
  }

  public async stop(): Promise<void> {
    this.serverDesired = false;
    this.clearServerRetry();
    await this.runServerOp(() => this.stopGuarded());
  }

  public async configureKnownRepositories(rows: RepoRow[]): Promise<void> {
    for (const repo of uniqueRepos(rows)) {
      const checkoutPath = buildRepoCheckoutPath(this.config.reposRootPath, repo.owner, repo.repo);
      const wing = (await pathExists(checkoutPath)) ? await this.ensureProjectConfig(repo, checkoutPath) : buildRepoMemoryWing(repo);
      this.repoWings.set(repo.fullName.toLowerCase(), wing);
      this.repoCheckouts.set(wing, checkoutPath);
    }
  }

  public async registerRepository(repo: RepoMemoryIdentity, checkoutPath: string, options: { queueMine?: boolean } = {}): Promise<string> {
    if (!this.config.mempalaceRemoteEnabled) return buildRepoMemoryWing(repo);
    await this.ensureToken();
    const wing = await this.ensureProjectConfig(repo, checkoutPath);
    const changed = this.repoCheckouts.get(wing) !== checkoutPath || this.repoWings.get(repo.fullName.toLowerCase()) !== wing;
    this.repoWings.set(repo.fullName.toLowerCase(), wing);
    this.repoCheckouts.set(wing, checkoutPath);
    if (changed) {
      await this.writeGlobalConfig();
      if (this.serverDesired) {
        await this.restartServer().catch((error: unknown) =>
          this.logger.warn({ error, repo: repo.fullName }, "MemPalace federation server restart failed; recovery scheduled")
        );
      }
    } else if (this.serverDesired && !this.serverRunning) {
      await this.recoverServer().catch((error: unknown) =>
        this.logger.warn({ error, repo: repo.fullName }, "MemPalace federation server recovery failed; retry scheduled")
      );
    }
    if (options.queueMine && this.config.mempalaceRemoteMineOnSync) this.queueMainBranchMine(repo, checkoutPath, wing);
    return wing;
  }

  public async ensureWorktreeConfig(repo: RepoMemoryIdentity, worktreePath: string): Promise<string> {
    if (!this.config.mempalaceRemoteEnabled) return buildRepoMemoryWing(repo);
    // A tracked config checked out into the worktree wins outright.
    const worktreeExisting = await findProjectConfigPath(worktreePath);
    if (worktreeExisting) return this.ensureProjectConfig(repo, worktreePath, { allowInit: false });
    // Otherwise copy the main checkout's config (generated or hand-tuned, e.g.
    // via `mempalace-cli init`) so worktrees share the repo's wing and rooms.
    const checkoutPath = buildRepoCheckoutPath(this.config.reposRootPath, repo.owner, repo.repo);
    if (await pathExists(checkoutPath)) {
      const wing = await this.ensureProjectConfig(repo, checkoutPath);
      const sourcePath = await findProjectConfigPath(checkoutPath);
      if (sourcePath) {
        await mkdir(worktreePath, { recursive: true });
        await writeFile(join(worktreePath, "mempalace.yaml"), await readFile(sourcePath, "utf8"), "utf8");
        await this.ignoreGeneratedProjectConfig(worktreePath);
        return wing;
      }
    }
    return this.ensureProjectConfig(repo, worktreePath, { allowInit: false });
  }

  public queueMainBranchMine(repo: RepoMemoryIdentity, checkoutPath: string, wing: string): void {
    if (!this.config.mempalaceRemoteMineOnSync) return;
    if (!existsSync(this.config.mempalaceCliPath)) {
      this.logger.warn({ cliPath: this.config.mempalaceCliPath }, "MemPalace remote mine skipped: mempalace-cli not installed");
      return;
    }
    if (this.mineJobs.has(checkoutPath)) return;
    const job = this.runMainBranchMine(repo, checkoutPath, wing)
      .catch((error: unknown) => this.logger.warn({ error, repo: repo.fullName, wing }, "MemPalace remote mine failed"))
      .finally(() => this.mineJobs.delete(checkoutPath));
    this.mineJobs.set(checkoutPath, job);
  }

  private ensureProjectConfig(
    repo: RepoMemoryIdentity,
    checkoutPath: string,
    options: { allowInit?: boolean } = {}
  ): Promise<string> {
    // Serialize per checkout path: concurrent requests for the same repo
    // would otherwise race `mempalace-cli init` / template writes against the
    // same mempalace.yaml. Each queued call still re-reads the file, so later
    // callers observe whatever the earlier one wrote.
    const prev = this.projectConfigOps.get(checkoutPath) ?? Promise.resolve();
    const op = prev
      .catch(() => undefined)
      .then(() => this.ensureProjectConfigUnlocked(repo, checkoutPath, options));
    this.projectConfigOps.set(checkoutPath, op);
    op
      .catch(() => undefined)
      .finally(() => {
        if (this.projectConfigOps.get(checkoutPath) === op) this.projectConfigOps.delete(checkoutPath);
      });
    return op;
  }

  private async ensureProjectConfigUnlocked(
    repo: RepoMemoryIdentity,
    checkoutPath: string,
    options: { allowInit?: boolean } = {}
  ): Promise<string> {
    // Init derives the wing from the directory leaf, which for request
    // worktrees is the request id — callers pass allowInit: false there.
    const allowInit = options.allowInit ?? true;
    await mkdir(checkoutPath, { recursive: true });
    const primaryPath = join(checkoutPath, "mempalace.yaml");
    const existingPath = await findProjectConfigPath(checkoutPath);
    if (existingPath) {
      const contents = await readFile(existingPath, "utf8");
      const wing = parseProjectConfigWing(contents);
      if (!wing) throw new MemPalaceRemoteConfigError("Existing MemPalace project config has no wing: " + existingPath);
      // Regenerate configs we previously generated under the old hashed wing
      // naming; configs authored outside Actuarius are honored as-is.
      const expected = buildRepoMemoryWing(repo);
      if (wing !== expected && contents.startsWith(GENERATED_HEADER)) {
        this.logger.info({ repo: repo.fullName, oldWing: wing, wing: expected }, "Migrating generated MemPalace project config to new wing name");
        return this.writeProjectConfig(repo, checkoutPath, primaryPath, allowInit, { overwrite: true });
      }
      return wing;
    }
    return this.writeProjectConfig(repo, checkoutPath, primaryPath, allowInit, {});
  }

  /**
   * Create the project config, preferring `mempalace-cli init` (which detects
   * rooms from the repo structure) and falling back to the generic template
   * when init is unavailable or fails.
   */
  private async writeProjectConfig(
    repo: RepoMemoryIdentity,
    checkoutPath: string,
    primaryPath: string,
    allowInit: boolean,
    options: { overwrite?: boolean }
  ): Promise<string> {
    if (allowInit) {
      const initWing = await this.runProjectInit(repo, checkoutPath, options);
      if (initWing) {
        await this.ignoreGeneratedProjectConfig(checkoutPath);
        return initWing;
      }
    }
    const wing = buildRepoMemoryWing(repo);
    await writeFile(primaryPath, renderGeneratedProjectConfig(wing, this.config.mempalaceRemoteName), "utf8");
    await this.ignoreGeneratedProjectConfig(checkoutPath);
    return wing;
  }

  private async runProjectInit(
    repo: RepoMemoryIdentity,
    checkoutPath: string,
    options: { overwrite?: boolean }
  ): Promise<string | null> {
    if (!existsSync(this.config.mempalaceCliPath)) return null;
    const args = ["--palace", this.config.mempalacePalacePath, "init", checkoutPath];
    if (options.overwrite) args.push("--yes");
    try {
      await spawnCollect(this.config.mempalaceCliPath, args, {
        cwd: checkoutPath,
        env: this.buildProcessEnv(),
        timeoutMs: this.config.mempalaceRemoteMineTimeoutMs,
        maxBuffer: 4 * 1024 * 1024
      });
    } catch (error) {
      this.logger.warn({ error, repo: repo.fullName, checkoutPath }, "mempalace-cli init failed; falling back to generated project config");
      return null;
    }
    const configPath = join(checkoutPath, "mempalace.yaml");
    if (!(await pathExists(configPath))) {
      this.logger.warn({ repo: repo.fullName, checkoutPath }, "mempalace-cli init succeeded but wrote no mempalace.yaml; falling back to generated project config");
      return null;
    }
    const wing = parseProjectConfigWing(await readFile(configPath, "utf8"));
    if (!wing) {
      this.logger.warn({ repo: repo.fullName, checkoutPath }, "mempalace-cli init config has no wing; falling back to generated project config");
      return null;
    }
    this.logger.info({ repo: repo.fullName, wing, checkoutPath }, "MemPalace project config created via mempalace-cli init");
    return wing;
  }

  private async ignoreGeneratedProjectConfig(checkoutPath: string): Promise<void> {
    try {
      const result = await spawnCollect("git", ["-C", checkoutPath, "rev-parse", "--git-common-dir"], {
        cwd: checkoutPath,
        timeoutMs: 10_000,
        maxBuffer: 64 * 1024
      });
      const rawGitDir = result.stdout.trim();
      if (!rawGitDir) return;
      const excludePath = join(resolve(checkoutPath, rawGitDir), "info", "exclude");
      await mkdir(dirname(excludePath), { recursive: true });
      const current = (await pathExists(excludePath)) ? await readFile(excludePath, "utf8") : "";
      if (!current.split(/\r?\n/u).some((line) => line.trim() === "mempalace.yaml")) {
        await appendFile(excludePath, (current.endsWith("\n") || current.length === 0 ? "" : "\n") + "mempalace.yaml\n", "utf8");
      }
    } catch (error) {
      this.logger.debug({ error, checkoutPath }, "Could not add generated mempalace.yaml to git exclude");
    }
  }

  private ensureToken(): Promise<string> {
    if (this.remoteToken) return Promise.resolve(this.remoteToken);
    this.tokenPromise ??= this.createToken().catch((error: unknown) => {
      this.tokenPromise = null;
      throw error;
    });
    return this.tokenPromise;
  }

  private async createToken(): Promise<string> {
    const tokenFile = this.config.mempalaceRemoteTokenFile;
    await mkdir(dirname(tokenFile), { recursive: true });
    const entries = await readTokenEntries(tokenFile);
    const configuredToken = this.config.mempalaceRemoteToken?.trim();
    const existingToken = entries.find((entry) => entry.enabled !== false && typeof entry.token === "string")?.token;
    const token = configuredToken || (typeof existingToken === "string" ? existingToken : randomBytes(32).toString("base64url"));
    const withoutLocal = entries.filter((entry) => entry.name !== "actuarius-local");
    withoutLocal.unshift({ token, name: "actuarius-local", enabled: true });
    await writeFile(tokenFile, JSON.stringify(withoutLocal, null, 2) + "\n", { encoding: "utf8", mode: 0o600 });
    process.env.MEMPALACE_REMOTE_TOKEN = token;
    this.remoteToken = token;
    return token;
  }

  private async writeGlobalConfig(): Promise<void> {
    const write = this.writeConfigPromise.catch(() => undefined).then(() => this.writeGlobalConfigOnce());
    this.writeConfigPromise = write.catch(() => undefined);
    await write;
  }

  private async writeGlobalConfigOnce(): Promise<void> {
    await this.ensureToken();
    const configDir = join(this.homeDir, ".mempalace");
    const configPath = join(configDir, "config.json");
    await mkdir(configDir, { recursive: true });
    const current = await readJsonObject(configPath);

    const server = isRecord(current.server) ? { ...current.server } : {};
    const existingCheckouts = isRecord(server.checkouts) ? server.checkouts : {};
    const checkouts: Record<string, string> = { ...existingCheckouts } as Record<string, string>;
    for (const [wing, checkoutPath] of this.repoCheckouts.entries()) checkouts[wing] = checkoutPath;

    const federation = isRecord(current.federation) ? { ...current.federation } : {};
    const existingRemotes = Array.isArray(federation.remotes) ? federation.remotes.filter(isRecord) : [];
    const remotes = existingRemotes.filter((remote) => remote.name !== this.config.mempalaceRemoteName);
    remotes.push({
      name: this.config.mempalaceRemoteName,
      url: this.config.mempalaceRemoteUrl,
      token_env: "MEMPALACE_REMOTE_TOKEN",
      timeout_ms: this.config.mempalaceRemoteTimeoutMs
    });

    const existingWings = isRecord(federation.wings) ? federation.wings : {};
    const wings: Record<string, unknown> = { ...existingWings };
    for (const wing of this.repoCheckouts.keys()) {
      wings[wing] = { mode: "combined", remote: this.config.mempalaceRemoteName, write: "remote" };
    }

    // Route the knowledge graph through the remote store so KG facts recorded
    // by container agents are visible to federated peers. KG routing is a
    // single global rule in mempalace (not per-wing); an operator-authored
    // rule already present in the config is preserved.
    const kg = isRecord(federation.kg)
      ? federation.kg
      : { mode: "combined", remote: this.config.mempalaceRemoteName, write: "remote" };

    const nextConfig = {
      ...current,
      version: 1,
      palace_path: this.config.mempalacePalacePath,
      server: {
        ...server,
        bind: this.config.mempalaceRemoteBind,
        token_file: this.config.mempalaceRemoteTokenFile,
        checkouts
      },
      federation: {
        ...federation,
        remotes,
        default_mode: typeof federation.default_mode === "string" ? federation.default_mode : "local",
        wings,
        kg
      }
    };
    await writeFile(configPath, JSON.stringify(nextConfig, null, 2) + "\n", "utf8");
  }

  private buildProcessEnv(): NodeJS.ProcessEnv {
    return {
      ...process.env,
      MEMPALACE_REMOTE_TOKEN: this.remoteToken ?? process.env.MEMPALACE_REMOTE_TOKEN ?? "",
      MEMPALACE_EMBED_ALLOW_DOWNLOADS: "1"
    };
  }

  // ── Server lifecycle ──────────────────────────────────────────────────────
  // `serverDesired` is the intent (should the federation server be up). The live
  // process handle is an implementation detail of start/stopServerProcess, so a
  // failed restart or an unexpected crash can recover — via the next repository
  // registration (`recoverServer`) or a background retry — instead of leaving
  // federation down for every repo until the bot restarts. All transitions run
  // through `runServerOp` so a start can never race a stop.

  private runServerOp(op: () => Promise<void>): Promise<void> {
    const run = this.serverOp.then(op, op);
    this.serverOp = run.then(() => undefined, () => undefined);
    return run;
  }

  private async bringServerUp(): Promise<void> {
    await this.runServerOp(() => this.startGuarded());
  }

  private async restartServer(): Promise<void> {
    await this.runServerOp(async () => {
      await this.stopGuarded();
      await this.startGuarded();
    });
  }

  private async recoverServer(): Promise<void> {
    await this.runServerOp(async () => {
      if (this.serverRunning) return;
      await this.startGuarded();
    });
  }

  private async startGuarded(): Promise<void> {
    if (this.serverRunning) return;
    try {
      await this.startServerProcess();
      this.serverRunning = true;
    } catch (error) {
      this.serverRunning = false;
      this.scheduleServerRetry();
      throw error;
    }
  }

  private async stopGuarded(): Promise<void> {
    this.clearServerRetry();
    try {
      await this.stopServerProcess();
    } finally {
      this.serverRunning = false;
    }
  }

  private scheduleServerRetry(): void {
    if (!this.serverDesired || this.serverRetryTimer) return;
    const timer = setTimeout(() => {
      this.serverRetryTimer = null;
      if (!this.serverDesired || this.serverRunning) return;
      void this.recoverServer().catch((error: unknown) =>
        this.logger.warn({ error }, "MemPalace federation server retry attempt failed; will retry")
      );
    }, MemPalaceRemoteService.SERVER_RETRY_DELAY_MS);
    timer.unref?.();
    this.serverRetryTimer = timer;
  }

  private clearServerRetry(): void {
    if (this.serverRetryTimer) {
      clearTimeout(this.serverRetryTimer);
      this.serverRetryTimer = null;
    }
  }

  /** Spawn `mempalace-cli serve` and resolve once it reports healthy. Overridable in tests. */
  protected async startServerProcess(): Promise<void> {
    if (this.server) return;
    await mkdir(this.config.mempalaceRemotePalacePath, { recursive: true });
    const args = [
      "--palace",
      this.config.mempalaceRemotePalacePath,
      "serve",
      "--bind",
      this.config.mempalaceRemoteBind,
      "--token-file",
      this.config.mempalaceRemoteTokenFile
    ];

    this.expectedServerExit = false;
    const child = spawn(this.config.mempalaceCliPath, args, { env: this.buildProcessEnv(), stdio: ["ignore", "pipe", "pipe"] });
    this.server = child;
    createInterface({ input: child.stdout! }).on("line", (line) => {
      if (this.expectedServerExit) return;
      this.logger.debug({ line }, "mempalace-cli serve stdout");
    });
    createInterface({ input: child.stderr! }).on("line", (line) => {
      if (this.expectedServerExit) return;
      this.logger.info({ line }, "mempalace-cli serve");
    });
    child.on("error", (error) => this.logger.error({ error }, "MemPalace federation server process error"));
    child.on("close", (code) => {
      const expected = this.expectedServerExit;
      if (this.server === child) {
        this.server = null;
        this.serverRunning = false;
      }
      if (!expected) {
        this.logger.warn({ code }, "MemPalace federation server exited unexpectedly");
        this.scheduleServerRetry();
      }
    });

    try {
      await this.waitForHealth();
    } catch (error) {
      // Health never came up — tear down this (possibly hung) process so a retry
      // restarts cleanly instead of adopting a zombie handle as "running".
      this.expectedServerExit = true;
      if (!child.killed) child.kill("SIGKILL");
      if (this.server === child) this.server = null;
      throw error;
    }
    this.logger.info(
      { bind: this.config.mempalaceRemoteBind, url: this.config.mempalaceRemoteUrl, palacePath: this.config.mempalaceRemotePalacePath },
      "MemPalace federation server ready"
    );
  }

  /** Terminate the running `serve` process. Overridable in tests. */
  protected async stopServerProcess(): Promise<void> {
    const child = this.server;
    if (!child) return;
    this.expectedServerExit = true;
    await new Promise<void>((resolveDone) => {
      const timer = setTimeout(() => {
        if (!child.killed) child.kill("SIGKILL");
        resolveDone();
      }, 5_000);
      child.once("close", () => {
        clearTimeout(timer);
        resolveDone();
      });
      child.kill("SIGTERM");
    });
    if (this.server === child) this.server = null;
  }

  private async waitForHealth(): Promise<void> {
    const healthUrl = new URL("/v1/health", this.config.mempalaceRemoteUrl).toString();
    const deadline = Date.now() + 15_000;
    let lastError: unknown = null;
    while (Date.now() < deadline) {
      if (!this.server) throw new Error("MemPalace federation server exited before it became healthy");
      try {
        const response = await fetch(healthUrl, { signal: AbortSignal.timeout(2_000) });
        if (response.ok) return;
        lastError = new Error("health returned HTTP " + response.status);
      } catch (error) {
        lastError = error;
      }
      await new Promise((resolveDelay) => setTimeout(resolveDelay, 250));
    }
    throw new Error("MemPalace federation server did not become healthy: " + (lastError instanceof Error ? lastError.message : String(lastError)));
  }

  private async runMainBranchMine(repo: RepoMemoryIdentity, checkoutPath: string, wing: string): Promise<void> {
    const args = ["--palace", this.config.mempalacePalacePath, "mine", checkoutPath];
    if (this.config.mempalaceRemoteMineBatchSize > 0) args.push("--batch-size", String(this.config.mempalaceRemoteMineBatchSize));
    this.logger.info({ repo: repo.fullName, wing, checkoutPath }, "MemPalace remote mine queued");
    const result = await spawnCollect(this.config.mempalaceCliPath, args, {
      cwd: checkoutPath,
      env: this.buildProcessEnv(),
      timeoutMs: this.config.mempalaceRemoteMineTimeoutMs,
      maxBuffer: 4 * 1024 * 1024
    });
    this.logger.info({ repo: repo.fullName, wing, stdout: result.stdout.trim(), stderr: result.stderr.trim() }, "MemPalace remote mine completed");
  }
}
