import { spawn, type ChildProcess } from "node:child_process";
import { existsSync } from "node:fs";
import { access, appendFile, chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import { createInterface } from "node:readline";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import type { Logger } from "pino";
import { parseDocument } from "yaml";
import type { AppConfig } from "../config.js";
import type { RepoRow } from "../db/types.js";
import { spawnCollect } from "../utils/spawnCollect.js";
import { configureAgentPalaceHttp } from "./agentPalaceHttpConfig.js";
import { MemPalaceClient } from "./memPalaceClient.js";
import { buildRepoCheckoutPath } from "./gitWorkspaceService.js";

const GENERATED_HEADER = "# Generated by Actuarius. Do not commit; this file routes repo memory to MemPalace.";
const DEFAULT_ROOMS = [
  { name: "src", keywords: ["src", "source", "code", "implementation"] },
  { name: "tests", keywords: ["test", "tests", "spec", "fixture"] },
  { name: "docs", keywords: ["doc", "docs", "readme", "guide"] },
  { name: "configuration", keywords: ["config", "docker", "deploy", "infra", "terraform"] },
  { name: "general", keywords: [] }
] as const;

export interface RepoMemoryIdentity {
  owner: string;
  repo: string;
  fullName: string;
}

/**
 * Thrown for deterministic startup failures that a retry cannot fix (a
 * missing binary, a malformed existing project config) — as opposed to the
 * federation server failing its health check, which can be transient. Callers
 * (see memPalaceRemoteStartup.ts) use this to skip retrying.
 */
export class MemPalaceRemoteConfigError extends Error {
  public constructor(message: string) {
    super(message);
    this.name = "MemPalaceRemoteConfigError";
  }
}

export interface MemPalaceRemoteServiceOptions {
  homeDir?: string;
}

interface TokenEntry {
  token?: unknown;
  name?: unknown;
  enabled?: unknown;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function findProjectConfigPath(dir: string): Promise<string | null> {
  const nativePath = join(dir, "agentpalace.yaml");
  if (await pathExists(nativePath)) return nativePath;
  const primaryPath = join(dir, "mempalace.yaml");
  if (await pathExists(primaryPath)) return primaryPath;
  const legacyPath = join(dir, "mempal.yaml");
  if (await pathExists(legacyPath)) return legacyPath;
  return null;
}

function sanitizeWingPart(value: string): string {
  const normalized = value.trim().toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  return normalized || "repo";
}

export function buildRepoMemoryWing(repo: RepoMemoryIdentity): string {
  // Mirrors `agentpalace init` naming (wing_<directory-name>) so repo wings
  // merge by name with palaces initialised locally under MemPalace federation.
  // Repos with identical names but different owners would share a wing; a
  // single-guild deployment connects few repos, so this is accepted.
  return "wing_" + sanitizeWingPart(repo.repo);
}

export function parseProjectConfigWing(configText: string): string | null {
  for (const rawLine of configText.split(/\r?\n/u)) {
    const line = rawLine.trim();
    const match = /^wing\s*:\s*["']?([^"'#\s]+)["']?\s*(?:#.*)?$/u.exec(line);
    if (match?.[1]) return match[1];
  }
  return null;
}

function renderGeneratedProjectConfig(wing: string): string {
  const lines = [
    GENERATED_HEADER,
    "wing: " + wing,
    "routing:",
    "  mode: local",
    "rooms:"
  ];
  for (const room of DEFAULT_ROOMS) {
    lines.push("  - name: " + room.name);
    lines.push(room.keywords.length > 0 ? "    keywords: [" + room.keywords.join(", ") + "]" : "    keywords: []");
  }
  return lines.join("\n") + "\n";
}

function uniqueRepos(rows: RepoRow[]): RepoMemoryIdentity[] {
  const seen = new Set<string>();
  const repos: RepoMemoryIdentity[] = [];
  for (const row of rows) {
    const key = row.full_name.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    repos.push({ owner: row.owner, repo: row.repo, fullName: row.full_name });
  }
  return repos;
}

async function readJsonObject(path: string): Promise<Record<string, unknown>> {
  if (!(await pathExists(path))) return {};
  try {
    const parsed = JSON.parse(await readFile(path, "utf8")) as unknown;
    return isRecord(parsed) ? parsed : {};
  } catch {
    return {};
  }
}

async function readTokenEntries(path: string): Promise<TokenEntry[]> {
  if (!(await pathExists(path))) return [];
  try {
    const parsed = JSON.parse(await readFile(path, "utf8")) as unknown;
    return Array.isArray(parsed) ? parsed.filter(isRecord) : [];
  } catch {
    return [];
  }
}

export class MemPalaceRemoteService {
  private readonly config: AppConfig;
  private readonly logger: Logger;
  private readonly homeDir: string;
  private readonly repoCheckouts = new Map<string, string>();
  private readonly repoWings = new Map<string, string>();
  private readonly mineJobs = new Map<string, Promise<void>>();
  private readonly projectConfigOps = new Map<string, Promise<string>>();
  private static readonly SERVER_RETRY_DELAY_MS = 30_000;
  private server: ChildProcess | null = null;
  private serverRunning = false;
  private serverDesired = false;
  private serverOp: Promise<void> = Promise.resolve();
  private serverRetryTimer: ReturnType<typeof setTimeout> | null = null;
  private expectedServerExit = false;
  private remoteToken: string | null = null;
  private tokenPromise: Promise<string> | null = null;
  private writeConfigPromise: Promise<void> = Promise.resolve();
  private healthAbort: AbortController | null = null;
  private startupSignal: AbortSignal | undefined;

  public constructor(config: AppConfig, logger: Logger, options: MemPalaceRemoteServiceOptions = {}) {
    this.config = config;
    this.logger = logger;
    this.homeDir = options.homeDir ?? homedir();
  }

  public async start(existingRepos: RepoRow[] = [], signal?: AbortSignal): Promise<void> {
    this.startupSignal = signal;
    signal?.throwIfAborted();
    if (!this.config.mempalaceRemoteEnabled && !this.config.mempalaceEnabled) return;
    if (!existsSync(this.config.mempalaceCliPath)) {
      throw new MemPalaceRemoteConfigError("agentpalace binary not found at " + this.config.mempalaceCliPath);
    }
    await this.ensureToken();
    await this.configureKnownRepositories(existingRepos);
    await this.writeGlobalConfig();
    this.serverDesired = true;
    await this.bringServerUp();
    await configureAgentPalaceHttp(this.homeDir, this.mcpUrl, await this.ensureToken(), this.homeDir === homedir() ? process.env.XDG_CONFIG_HOME : undefined);
  }

  public get mcpUrl(): string { return new URL("/mcp", this.config.mempalaceRemoteUrl).toString(); }
  public async getMcpToken(): Promise<string> { return this.ensureToken(); }

  public async stop(): Promise<void> {
    this.serverDesired = false;
    this.clearServerRetry();
    this.healthAbort?.abort();
    await this.runServerOp(() => this.stopGuarded());
  }

  public async configureKnownRepositories(rows: RepoRow[]): Promise<void> {
    for (const repo of uniqueRepos(rows)) {
      const checkoutPath = buildRepoCheckoutPath(this.config.reposRootPath, repo.owner, repo.repo);
      const wing = (await pathExists(checkoutPath)) ? await this.ensureProjectConfig(repo, checkoutPath) : buildRepoMemoryWing(repo);
      this.repoWings.set(repo.fullName.toLowerCase(), wing);
      this.repoCheckouts.set(wing, checkoutPath);
    }
  }

  public async registerRepository(repo: RepoMemoryIdentity, checkoutPath: string, options: { queueMine?: boolean } = {}): Promise<string> {
    if (!this.config.mempalaceRemoteEnabled && !this.config.mempalaceEnabled) return buildRepoMemoryWing(repo);
    await this.ensureToken();
    const wing = await this.ensureProjectConfig(repo, checkoutPath);
    const changed = this.repoCheckouts.get(wing) !== checkoutPath || this.repoWings.get(repo.fullName.toLowerCase()) !== wing;
    this.repoWings.set(repo.fullName.toLowerCase(), wing);
    this.repoCheckouts.set(wing, checkoutPath);
    if (changed) {
      await this.writeGlobalConfig();
      if (this.serverDesired && this.serverRunning) {
        // 0.1.47 snapshots server.checkouts at startup. Keep active MCP calls
        // alive; new source-resolution mappings take effect on the next start.
        this.logger.info({ repo: repo.fullName }, "AgentPalace checkout mapping saved; source retrieval available after the next server restart");
      }
    }
    if (this.serverDesired && !this.serverRunning) {
      await this.recoverServer().catch((error: unknown) =>
        this.logger.warn({ error, repo: repo.fullName }, "MemPalace federation server recovery failed; retry scheduled")
      );
    }
    if (options.queueMine && this.config.mempalaceRemoteMineOnSync) this.queueMainBranchMine(repo, checkoutPath, wing);
    return wing;
  }

  public async ensureWorktreeConfig(repo: RepoMemoryIdentity, worktreePath: string): Promise<string> {
    if (!this.config.mempalaceRemoteEnabled && !this.config.mempalaceEnabled) return buildRepoMemoryWing(repo);
    // A tracked config checked out into the worktree wins outright.
    const worktreeExisting = await findProjectConfigPath(worktreePath);
    if (worktreeExisting) return this.ensureProjectConfig(repo, worktreePath, { allowInit: false });
    // Otherwise copy the main checkout's config (generated or hand-tuned, e.g.
    // via `agentpalace init`) so worktrees share the repo's wing and rooms.
    const checkoutPath = buildRepoCheckoutPath(this.config.reposRootPath, repo.owner, repo.repo);
    if (await pathExists(checkoutPath)) {
      const wing = await this.ensureProjectConfig(repo, checkoutPath);
      const sourcePath = await findProjectConfigPath(checkoutPath);
      if (sourcePath) {
        await mkdir(worktreePath, { recursive: true });
        await writeFile(join(worktreePath, "agentpalace.yaml"), await readFile(sourcePath, "utf8"), "utf8");
        await this.ignoreGeneratedProjectConfig(worktreePath);
        return wing;
      }
    }
    return this.ensureProjectConfig(repo, worktreePath, { allowInit: false });
  }

  public queueMainBranchMine(repo: RepoMemoryIdentity, checkoutPath: string, wing: string): void {
    if (!this.config.mempalaceRemoteMineOnSync) return;
    if (!existsSync(this.config.mempalaceCliPath)) {
      this.logger.warn({ cliPath: this.config.mempalaceCliPath }, "MemPalace remote mine skipped: agentpalace not installed");
      return;
    }
    if (this.mineJobs.has(checkoutPath)) return;
    const job = this.runMainBranchMine(repo, checkoutPath, wing)
      .catch((error: unknown) => this.logger.warn({ error, repo: repo.fullName, wing }, "MemPalace remote mine failed"))
      .finally(() => this.mineJobs.delete(checkoutPath));
    this.mineJobs.set(checkoutPath, job);
  }

  private ensureProjectConfig(
    repo: RepoMemoryIdentity,
    checkoutPath: string,
    options: { allowInit?: boolean } = {}
  ): Promise<string> {
    // Serialize per checkout path: concurrent requests for the same repo
    // would otherwise race `agentpalace init` / template writes against the
    // same mempalace.yaml. Each queued call still re-reads the file, so later
    // callers observe whatever the earlier one wrote.
    const prev = this.projectConfigOps.get(checkoutPath) ?? Promise.resolve();
    const op = prev
      .catch(() => undefined)
      .then(() => this.ensureProjectConfigUnlocked(repo, checkoutPath, options));
    this.projectConfigOps.set(checkoutPath, op);
    op
      .catch(() => undefined)
      .finally(() => {
        if (this.projectConfigOps.get(checkoutPath) === op) this.projectConfigOps.delete(checkoutPath);
      });
    return op;
  }

  private async ensureProjectConfigUnlocked(
    repo: RepoMemoryIdentity,
    checkoutPath: string,
    options: { allowInit?: boolean } = {}
  ): Promise<string> {
    // Init derives the wing from the directory leaf, which for request
    // worktrees is the request id — callers pass allowInit: false there.
    const allowInit = options.allowInit ?? true;
    await mkdir(checkoutPath, { recursive: true });
    const primaryPath = join(checkoutPath, "agentpalace.yaml");
    const existingPath = await findProjectConfigPath(checkoutPath);
    if (existingPath) {
      const contents = await readFile(existingPath, "utf8");
      const wing = parseProjectConfigWing(contents);
      if (!wing) throw new MemPalaceRemoteConfigError("Existing MemPalace project config has no wing: " + existingPath);
      // Regenerate configs we previously generated under the old hashed wing
      // naming; configs authored outside Actuarius are honored as-is.
      const expected = buildRepoMemoryWing(repo);
      if (wing !== expected && contents.startsWith(GENERATED_HEADER)) {
        this.logger.info({ repo: repo.fullName, oldWing: wing, wing: expected }, "Migrating generated MemPalace project config to new wing name");
        return this.writeProjectConfig(repo, checkoutPath, primaryPath, allowInit, { overwrite: true });
      }
      const document = parseDocument(contents);
      if (document.errors.length) throw new MemPalaceRemoteConfigError("Invalid project YAML: " + existingPath);
      if (document.getIn(["routing", "remote"]) === this.config.mempalaceRemoteName) {
        document.setIn(["routing", "mode"], "local");
        document.deleteIn(["routing", "remote"]);
        document.deleteIn(["routing", "write"]);
        // Create the native override without changing a tracked legacy file.
        await writeFile(primaryPath, document.toString(), "utf8");
        await this.ignoreGeneratedProjectConfig(checkoutPath);
      }
      return wing;
    }
    return this.writeProjectConfig(repo, checkoutPath, primaryPath, allowInit, {});
  }

  /**
   * Create the project config, preferring `agentpalace init` (which detects
   * rooms from the repo structure) and falling back to the generic template
   * when init is unavailable or fails.
   */
  private async writeProjectConfig(
    repo: RepoMemoryIdentity,
    checkoutPath: string,
    primaryPath: string,
    allowInit: boolean,
    options: { overwrite?: boolean }
  ): Promise<string> {
    if (allowInit) {
      const initWing = await this.runProjectInit(repo, checkoutPath, options);
      if (initWing) {
        await this.ignoreGeneratedProjectConfig(checkoutPath);
        return initWing;
      }
    }
    const wing = buildRepoMemoryWing(repo);
    await writeFile(primaryPath, renderGeneratedProjectConfig(wing), "utf8");
    await this.ignoreGeneratedProjectConfig(checkoutPath);
    return wing;
  }

  private async runProjectInit(
    repo: RepoMemoryIdentity,
    checkoutPath: string,
    options: { overwrite?: boolean }
  ): Promise<string | null> {
    if (!existsSync(this.config.mempalaceCliPath)) return null;
    const args = ["--palace", this.config.mempalaceRemotePalacePath, "init", checkoutPath];
    if (options.overwrite) args.push("--yes");
    try {
      await spawnCollect(this.config.mempalaceCliPath, args, {
        cwd: checkoutPath,
        env: this.buildProcessEnv(),
        timeoutMs: this.config.mempalaceRemoteMineTimeoutMs,
        maxBuffer: 4 * 1024 * 1024
      });
    } catch (error) {
      this.logger.warn({ error, repo: repo.fullName, checkoutPath }, "agentpalace init failed; falling back to generated project config");
      return null;
    }
    const configPath = join(checkoutPath, "agentpalace.yaml");
    if (!(await pathExists(configPath))) {
      this.logger.warn({ repo: repo.fullName, checkoutPath }, "agentpalace init succeeded but wrote no mempalace.yaml; falling back to generated project config");
      return null;
    }
    const wing = parseProjectConfigWing(await readFile(configPath, "utf8"));
    if (!wing) {
      this.logger.warn({ repo: repo.fullName, checkoutPath }, "agentpalace init config has no wing; falling back to generated project config");
      return null;
    }
    this.logger.info({ repo: repo.fullName, wing, checkoutPath }, "MemPalace project config created via agentpalace init");
    return wing;
  }

  private async ignoreGeneratedProjectConfig(checkoutPath: string): Promise<void> {
    try {
      const result = await spawnCollect("git", ["-C", checkoutPath, "rev-parse", "--git-common-dir"], {
        cwd: checkoutPath,
        timeoutMs: 10_000,
        maxBuffer: 64 * 1024
      });
      const rawGitDir = result.stdout.trim();
      if (!rawGitDir) return;
      const excludePath = join(resolve(checkoutPath, rawGitDir), "info", "exclude");
      await mkdir(dirname(excludePath), { recursive: true });
      const current = (await pathExists(excludePath)) ? await readFile(excludePath, "utf8") : "";
      if (!current.split(/\r?\n/u).some((line) => line.trim() === "agentpalace.yaml")) {
        await appendFile(excludePath, (current.endsWith("\n") || current.length === 0 ? "" : "\n") + "agentpalace.yaml\n", "utf8");
      }
    } catch (error) {
      this.logger.debug({ error, checkoutPath }, "Could not add generated mempalace.yaml to git exclude");
    }
  }

  private ensureToken(): Promise<string> {
    if (this.remoteToken) return Promise.resolve(this.remoteToken);
    this.tokenPromise ??= this.createToken().catch((error: unknown) => {
      this.tokenPromise = null;
      throw error;
    });
    return this.tokenPromise;
  }

  private async createToken(): Promise<string> {
    const tokenFile = this.config.mempalaceRemoteTokenFile;
    await mkdir(dirname(tokenFile), { recursive: true });
    const entries = await readTokenEntries(tokenFile);
    const configuredToken = this.config.mempalaceRemoteToken?.trim();
    const existingToken = entries.find((entry) => entry.name === "actuarius-local" && entry.enabled !== false && typeof entry.token === "string")?.token;
    const token = configuredToken || (typeof existingToken === "string" ? existingToken : randomBytes(32).toString("base64url"));
    const withoutLocal = entries.filter((entry) => entry.name !== "actuarius-local");
    withoutLocal.unshift({ token, name: "actuarius-local", enabled: true });
    if (await pathExists(tokenFile)) await chmod(tokenFile, 0o600);
    await writeFile(tokenFile, JSON.stringify(withoutLocal, null, 2) + "\n", { encoding: "utf8", mode: 0o600 });
    process.env.MEMPALACE_REMOTE_TOKEN = token;
    this.remoteToken = token;
    return token;
  }

  private async writeGlobalConfig(): Promise<void> {
    const write = this.writeConfigPromise.catch(() => undefined).then(() => this.writeGlobalConfigOnce());
    this.writeConfigPromise = write.catch(() => undefined);
    await write;
  }

  /**
   * True when a wing rule has exactly the shape this service writes, and can
   * therefore be safely dropped once its wing is no longer tracked. Anything
   * else is treated as operator-authored and preserved.
   */
  private isManagedWingRule(rule: unknown): boolean {
    if (!isRecord(rule)) return false;
    return (
      rule.mode === "combined" &&
      rule.remote === this.config.mempalaceRemoteName &&
      rule.write === "remote" &&
      Object.keys(rule).length === 3
    );
  }

  /**
   * True when a routing rule (wing, kg, or coordination) names the remote this
   * service used to manage. Removing that remote from `federation.remotes`
   * without rewriting such a rule makes mempalace-rs reject the whole config
   * (`resolve_rule` errors on an unknown remote), and every entry point that
   * loads it — `agentpalace serve --stdio`, `serve`, `mine`, `init` — fails to start. Any
   * surviving rule that points at the removed remote is therefore rewritten to
   * local rather than preserved verbatim.
   */
  private namesRemovedRemote(rule: unknown): boolean {
    return isRecord(rule) && rule.remote === this.config.mempalaceRemoteName;
  }

  private async writeGlobalConfigOnce(): Promise<void> {
    // Preserve the server authentication file; local harnesses use HTTP bearer auth.
    await this.ensureToken();
    const configDir = join(this.homeDir, ".mempalace");
    const configPath = join(configDir, "config.json");
    await mkdir(configDir, { recursive: true });
    const current = await readJsonObject(configPath);

    const server = isRecord(current.server) ? { ...current.server } : {};
    // server.checkouts is wholly bot-managed: rebuild rather than merge, so
    // entries for wings we no longer track (renames, disconnected repos)
    // don't accumulate forever.
    const checkouts: Record<string, string> = {};
    for (const [wing, checkoutPath] of this.repoCheckouts.entries()) checkouts[wing] = checkoutPath;

    const federation = isRecord(current.federation) ? { ...current.federation } : {};
    // Local HTTP MCP and federation REST share this process, so this host must
    // not define a remote pointing at itself. Preserve operator-authored
    // remotes to other hosts, but drop the managed self remote so writes no
    // longer bounce over loopback HTTP.
    const existingRemotes = Array.isArray(federation.remotes) ? federation.remotes.filter(isRecord) : [];
    const remotes = existingRemotes.filter((remote) => remote.name !== this.config.mempalaceRemoteName);

    // Keep operator-authored wing rules, but drop bot-managed rules for wings
    // we no longer track — each stale rule is a live route that will never
    // receive new content. Tracked wings route local: the shared palace is the
    // same store the serve hub exposes to federated peers. A surviving rule
    // that names the removed remote is rewritten to local, because leaving it
    // pointing at a remote that no longer exists breaks config loading.
    const existingWings = isRecord(federation.wings) ? federation.wings : {};
    const wings: Record<string, unknown> = {};
    for (const [wing, rule] of Object.entries(existingWings)) {
      if (this.isManagedWingRule(rule)) continue;
      if (this.namesRemovedRemote(rule)) {
        this.logger.warn(
          { wing, remote: this.config.mempalaceRemoteName },
          "Rewriting MemPalace wing rule that names the removed self remote to local routing"
        );
        wings[wing] = { mode: "local" };
        continue;
      }
      wings[wing] = rule;
    }
    for (const wing of this.repoCheckouts.keys()) {
      wings[wing] = { mode: "local" };
    }

    // Route the knowledge graph to the same shared palace. KG routing is a
    // single global rule in mempalace (not per-wing); an operator-authored
    // rule is preserved, but a rule this service previously wrote (the old
    // self-referential remote) migrates to local, as does any operator rule
    // still naming the removed remote.
    let kg: unknown;
    if (this.namesRemovedRemote(federation.kg)) {
      kg = { mode: "local" };
      if (!this.isManagedWingRule(federation.kg)) {
        this.logger.warn(
          { remote: this.config.mempalaceRemoteName },
          "Rewriting MemPalace kg rule that names the removed self remote to local routing"
        );
      }
    } else if (isRecord(federation.kg)) {
      kg = federation.kg;
    } else {
      kg = { mode: "local" };
    }

    // Coordination rules share the same unknown-remote failure mode, so a rule
    // naming the removed remote is rewritten too. Rules are otherwise left to
    // the operator.
    const existingCoordination = isRecord(federation.coordination) ? federation.coordination : {};
    const coordination: Record<string, unknown> = {};
    for (const [wing, rule] of Object.entries(existingCoordination)) {
      if (this.namesRemovedRemote(rule)) {
        this.logger.warn(
          { wing, remote: this.config.mempalaceRemoteName },
          "Rewriting MemPalace coordination rule that names the removed self remote to local routing"
        );
        coordination[wing] = { mode: "local" };
        continue;
      }
      coordination[wing] = rule;
    }

    const nextConfig = {
      ...current,
      version: 1,
      palace_path: this.config.mempalaceRemotePalacePath,
      server: {
        ...server,
        bind: this.config.mempalaceRemoteBind,
        token_file: this.config.mempalaceRemoteTokenFile,
        checkouts
      },
      federation: {
        ...federation,
        remotes,
        // HTTP MCP and federation REST resolve local routes in this same server.
        default_mode: "local",
        wings,
        kg,
        coordination
      }
    };
    await writeFile(configPath, JSON.stringify(nextConfig, null, 2) + "\n", { encoding: "utf8", mode: 0o600 });
    // mode only applies on create; tighten pre-existing files too since the
    // config holds the federation token file location and route rules.
    await chmod(configPath, 0o600);
  }

  private buildProcessEnv(): NodeJS.ProcessEnv {
    return {
      ...process.env,
      AGENTPALACE_CONFIG_DIR: join(this.homeDir, ".mempalace"),
      AGENTPALACE_PALACE_PATH: this.config.mempalaceRemotePalacePath,
      AGENTPALACE_EMBEDDING_PROFILE: this.config.mempalaceEmbeddingProfile,
      AGENTPALACE_EMBED_ALLOW_DOWNLOADS: "1"
    };
  }

  // ── Server lifecycle ──────────────────────────────────────────────────────
  // `serverDesired` is the intent (should the federation server be up). The live
  // process handle is an implementation detail of start/stopServerProcess, so a
  // failed restart or an unexpected crash can recover — via the next repository
  // registration (`recoverServer`) or a background retry — instead of leaving
  // federation down for every repo until the bot restarts. All transitions run
  // through `runServerOp` so a start can never race a stop.

  private runServerOp(op: () => Promise<void>): Promise<void> {
    const run = this.serverOp.then(op, op);
    this.serverOp = run.then(() => undefined, () => undefined);
    return run;
  }

  private async bringServerUp(): Promise<void> {
    await this.runServerOp(() => this.startGuarded());
  }

  private async recoverServer(): Promise<void> {
    await this.runServerOp(async () => {
      if (this.serverRunning) return;
      await this.startGuarded();
    });
  }

  private async startGuarded(): Promise<void> {
    if (this.serverRunning || !this.serverDesired) return;
    const abort = new AbortController();
    this.healthAbort = abort;
    const signal = this.startupSignal ? AbortSignal.any([abort.signal, this.startupSignal]) : abort.signal;
    try {
      signal.throwIfAborted();
      await this.startServerProcess(signal);
      signal.throwIfAborted();
      this.serverRunning = true;
    } catch (error) {
      this.serverRunning = false;
      this.scheduleServerRetry();
      throw error;
    } finally {
      if (this.healthAbort === abort) this.healthAbort = null;
    }
  }

  private async stopGuarded(): Promise<void> {
    this.clearServerRetry();
    try {
      await this.stopServerProcess();
    } finally {
      this.serverRunning = false;
    }
  }

  private scheduleServerRetry(): void {
    if (!this.serverDesired || this.serverRetryTimer) return;
    const timer = setTimeout(() => {
      this.serverRetryTimer = null;
      if (!this.serverDesired || this.serverRunning) return;
      void this.recoverServer().catch((error: unknown) =>
        this.logger.warn({ error }, "MemPalace federation server retry attempt failed; will retry")
      );
    }, MemPalaceRemoteService.SERVER_RETRY_DELAY_MS);
    timer.unref?.();
    this.serverRetryTimer = timer;
  }

  private clearServerRetry(): void {
    if (this.serverRetryTimer) {
      clearTimeout(this.serverRetryTimer);
      this.serverRetryTimer = null;
    }
  }

  /** Spawn `agentpalace serve` and resolve once it reports healthy. Overridable in tests. */
  protected async startServerProcess(signal: AbortSignal): Promise<void> {
    if (this.server) return;
    await mkdir(this.config.mempalaceRemotePalacePath, { recursive: true });
    const args = [
      "--palace",
      this.config.mempalaceRemotePalacePath,
      "serve",
      "--bind",
      this.config.mempalaceRemoteBind,
      "--token-file",
      this.config.mempalaceRemoteTokenFile
    ];

    this.expectedServerExit = false;
    const child = spawn(this.config.mempalaceCliPath, args, { env: this.buildProcessEnv(), stdio: ["ignore", "pipe", "pipe"] });
    this.server = child;
    createInterface({ input: child.stdout! }).on("line", (line) => {
      if (this.expectedServerExit) return;
      this.logger.debug({ line }, "agentpalace serve stdout");
    });
    createInterface({ input: child.stderr! }).on("line", (line) => {
      if (this.expectedServerExit) return;
      this.logger.info({ line }, "agentpalace serve");
    });
    child.on("error", (error) => this.logger.error({ error }, "MemPalace federation server process error"));
    child.on("close", (code) => {
      const expected = this.expectedServerExit;
      if (this.server === child) {
        this.server = null;
        this.serverRunning = false;
      }
      if (!expected) {
        this.logger.warn({ code }, "MemPalace federation server exited unexpectedly");
        this.scheduleServerRetry();
      }
    });

    try {
      await this.waitForHealth(signal);
    } catch (error) {
      // Health never came up — tear down this (possibly hung) process so a retry
      // restarts cleanly instead of adopting a zombie handle as "running".
      this.expectedServerExit = true;
      if (!child.killed) child.kill("SIGKILL");
      if (this.server === child) this.server = null;
      throw error;
    }
    this.logger.info(
      { bind: this.config.mempalaceRemoteBind, url: this.config.mempalaceRemoteUrl, palacePath: this.config.mempalaceRemotePalacePath },
      "MemPalace federation server ready"
    );
  }

  /** Terminate the running `serve` process. Overridable in tests. */
  protected async stopServerProcess(): Promise<void> {
    const child = this.server;
    if (!child) return;
    this.expectedServerExit = true;
    await new Promise<void>((resolveDone) => {
      const timer = setTimeout(() => {
        if (!child.killed) child.kill("SIGKILL");
        resolveDone();
      }, 5_000);
      child.once("close", () => {
        clearTimeout(timer);
        resolveDone();
      });
      child.kill("SIGTERM");
    });
    if (this.server === child) this.server = null;
  }

  private async waitForHealth(signal: AbortSignal): Promise<void> {
    const healthUrl = new URL("/v1/health", this.config.mempalaceRemoteUrl).toString();
    // A cold cache may need to download the quantized model before binding.
    // Killing that process after 15s repeatedly interrupted valid first starts.
    const deadline = Date.now() + 120_000;
    let lastError: unknown = null;
    while (Date.now() < deadline) {
      signal.throwIfAborted();
      if (!this.server) throw new Error("MemPalace federation server exited before it became healthy");
      try {
        const signals = [AbortSignal.timeout(2_000)];
        signals.push(signal);
        const response = await fetch(healthUrl, { signal: AbortSignal.any(signals) });
        if (response.ok) {
          const probe = new MemPalaceClient(this.mcpUrl, await this.ensureToken(), this.logger);
          const abortProbe = (): void => { void probe.stop(); };
          signal.addEventListener("abort", abortProbe, { once: true });
          try {
            signal.throwIfAborted();
            await probe.start();
            return;
          } finally {
            signal.removeEventListener("abort", abortProbe);
            await probe.stop();
          }
        }
        lastError = new Error("health returned HTTP " + response.status);
      } catch (error) {
        lastError = error;
      }
      await new Promise((resolveDelay) => setTimeout(resolveDelay, 250));
    }
    throw new Error("MemPalace federation server did not become healthy: " + (lastError instanceof Error ? lastError.message : String(lastError)));
  }

  private async runMainBranchMine(repo: RepoMemoryIdentity, checkoutPath: string, wing: string): Promise<void> {
    const args = ["--palace", this.config.mempalaceRemotePalacePath, "mine", checkoutPath];
    if (this.config.mempalaceRemoteMineBatchSize > 0) args.push("--batch-size", String(this.config.mempalaceRemoteMineBatchSize));
    this.logger.info({ repo: repo.fullName, wing, checkoutPath }, "MemPalace remote mine queued");
    const result = await spawnCollect(this.config.mempalaceCliPath, args, {
      cwd: checkoutPath,
      env: this.buildProcessEnv(),
      timeoutMs: this.config.mempalaceRemoteMineTimeoutMs,
      maxBuffer: 4 * 1024 * 1024
    });
    this.logger.info({ repo: repo.fullName, wing, stdout: result.stdout.trim(), stderr: result.stderr.trim() }, "MemPalace remote mine completed");
  }
}
