import { spawn, type ChildProcess } from "node:child_process";
import { existsSync } from "node:fs";
import { access, appendFile, chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import { createInterface } from "node:readline";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import type { Logger } from "pino";
import type { AppConfig } from "../config.js";
import type { RepoRow } from "../db/types.js";
import { spawnCollect } from "../utils/spawnCollect.js";
import { buildRepoCheckoutPath } from "./gitWorkspaceService.js";

const GENERATED_HEADER = "# Generated by Actuarius. Do not commit; this file routes repo memory to MemPalace.";
const DEFAULT_ROOMS = [
  { name: "src", keywords: ["src", "source", "code", "implementation"] },
  { name: "tests", keywords: ["test", "tests", "spec", "fixture"] },
  { name: "docs", keywords: ["doc", "docs", "readme", "guide"] },
  { name: "configuration", keywords: ["config", "docker", "deploy", "infra", "terraform"] },
  { name: "general", keywords: [] }
] as const;

export interface RepoMemoryIdentity {
  owner: string;
  repo: string;
  fullName: string;
}

export interface MemPalaceRemoteServiceOptions {
  homeDir?: string;
}

interface TokenEntry {
  token?: unknown;
  name?: unknown;
  enabled?: unknown;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function sanitizeWingPart(value: string): string {
  const normalized = value.trim().toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  return normalized || "repo";
}

export function buildRepoMemoryWing(repo: RepoMemoryIdentity): string {
  return "wing_repo_" + sanitizeWingPart(repo.owner) + "_" + sanitizeWingPart(repo.repo);
}

export function parseProjectConfigWing(configText: string): string | null {
  for (const rawLine of configText.split(/\r?\n/u)) {
    const line = rawLine.trim();
    const match = /^wing\s*:\s*["']?([^"'#\s]+)["']?\s*(?:#.*)?$/u.exec(line);
    if (match?.[1]) return match[1];
  }
  return null;
}

function renderGeneratedProjectConfig(wing: string, remoteName: string): string {
  const lines = [
    GENERATED_HEADER,
    "wing: " + wing,
    "routing:",
    "  mode: combined",
    "  remote: " + remoteName,
    "  write: remote",
    "rooms:"
  ];
  for (const room of DEFAULT_ROOMS) {
    lines.push("  - name: " + room.name);
    lines.push(room.keywords.length > 0 ? "    keywords: [" + room.keywords.join(", ") + "]" : "    keywords: []");
  }
  return lines.join("\n") + "\n";
}

function uniqueRepos(rows: RepoRow[]): RepoMemoryIdentity[] {
  const seen = new Set<string>();
  const repos: RepoMemoryIdentity[] = [];
  for (const row of rows) {
    const key = row.full_name.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    repos.push({ owner: row.owner, repo: row.repo, fullName: row.full_name });
  }
  return repos;
}

async function readJsonObject(path: string): Promise<Record<string, unknown>> {
  if (!(await pathExists(path))) return {};
  try {
    const parsed = JSON.parse(await readFile(path, "utf8")) as unknown;
    return isRecord(parsed) ? parsed : {};
  } catch {
    return {};
  }
}

async function readTokenEntries(path: string): Promise<TokenEntry[]> {
  if (!(await pathExists(path))) return [];
  try {
    const parsed = JSON.parse(await readFile(path, "utf8")) as unknown;
    return Array.isArray(parsed) ? parsed.filter(isRecord) : [];
  } catch {
    return [];
  }
}

export class MemPalaceRemoteService {
  private readonly config: AppConfig;
  private readonly logger: Logger;
  private readonly homeDir: string;
  private readonly repoCheckouts = new Map<string, string>();
  private readonly repoWings = new Map<string, string>();
  private readonly mineJobs = new Map<string, Promise<void>>();
  private server: ChildProcess | null = null;
  private expectedServerExit = false;
  private remoteToken: string | null = null;
  private tokenPromise: Promise<string> | null = null;
  private writeConfigPromise: Promise<void> = Promise.resolve();

  public constructor(config: AppConfig, logger: Logger, options: MemPalaceRemoteServiceOptions = {}) {
    this.config = config;
    this.logger = logger;
    this.homeDir = options.homeDir ?? homedir();
  }

  public async start(existingRepos: RepoRow[] = []): Promise<void> {
    if (!this.config.mempalaceRemoteEnabled) return;
    if (!existsSync(this.config.mempalaceCliPath)) {
      throw new Error("mempalace-cli binary not found at " + this.config.mempalaceCliPath);
    }
    await this.ensureToken();
    await this.configureKnownRepositories(existingRepos);
    await this.writeGlobalConfig();
    await this.startServer();
  }

  public async stop(): Promise<void> {
    await this.stopServer();
  }

  public async configureKnownRepositories(rows: RepoRow[]): Promise<void> {
    for (const repo of uniqueRepos(rows)) {
      const checkoutPath = buildRepoCheckoutPath(this.config.reposRootPath, repo.owner, repo.repo);
      const wing = (await pathExists(checkoutPath)) ? await this.ensureProjectConfig(repo, checkoutPath) : buildRepoMemoryWing(repo);
      this.repoWings.set(repo.fullName.toLowerCase(), wing);
      this.repoCheckouts.set(wing, checkoutPath);
    }
  }

  public async registerRepository(repo: RepoMemoryIdentity, checkoutPath: string, options: { queueMine?: boolean } = {}): Promise<string> {
    if (!this.config.mempalaceRemoteEnabled) return buildRepoMemoryWing(repo);
    await this.ensureToken();
    const wing = await this.ensureProjectConfig(repo, checkoutPath);
    const changed = this.repoCheckouts.get(wing) !== checkoutPath || this.repoWings.get(repo.fullName.toLowerCase()) !== wing;
    this.repoWings.set(repo.fullName.toLowerCase(), wing);
    this.repoCheckouts.set(wing, checkoutPath);
    await this.writeGlobalConfig();
    if (changed && this.server) await this.restartServer();
    if (options.queueMine && this.config.mempalaceRemoteMineOnSync) this.queueMainBranchMine(repo, checkoutPath, wing);
    return wing;
  }

  public async ensureWorktreeConfig(repo: RepoMemoryIdentity, worktreePath: string): Promise<string> {
    if (!this.config.mempalaceRemoteEnabled) return buildRepoMemoryWing(repo);
    return this.ensureProjectConfig(repo, worktreePath);
  }

  public queueMainBranchMine(repo: RepoMemoryIdentity, checkoutPath: string, wing: string): void {
    if (!this.config.mempalaceRemoteMineOnSync) return;
    if (!existsSync(this.config.mempalaceCliPath)) {
      this.logger.warn({ cliPath: this.config.mempalaceCliPath }, "MemPalace remote mine skipped: mempalace-cli not installed");
      return;
    }
    if (this.mineJobs.has(checkoutPath)) return;
    const job = this.runMainBranchMine(repo, checkoutPath, wing)
      .catch((error: unknown) => this.logger.warn({ error, repo: repo.fullName, wing }, "MemPalace remote mine failed"))
      .finally(() => this.mineJobs.delete(checkoutPath));
    this.mineJobs.set(checkoutPath, job);
  }

  private async ensureProjectConfig(repo: RepoMemoryIdentity, checkoutPath: string): Promise<string> {
    await mkdir(checkoutPath, { recursive: true });
    const primaryPath = join(checkoutPath, "mempalace.yaml");
    const legacyPath = join(checkoutPath, "mempal.yaml");
    const existingPath = (await pathExists(primaryPath)) ? primaryPath : (await pathExists(legacyPath)) ? legacyPath : null;
    if (existingPath) {
      const wing = parseProjectConfigWing(await readFile(existingPath, "utf8"));
      if (!wing) throw new Error("Existing MemPalace project config has no wing: " + existingPath);
      return wing;
    }
    const wing = buildRepoMemoryWing(repo);
    await writeFile(primaryPath, renderGeneratedProjectConfig(wing, this.config.mempalaceRemoteName), "utf8");
    await this.ignoreGeneratedProjectConfig(checkoutPath);
    return wing;
  }

  private async ignoreGeneratedProjectConfig(checkoutPath: string): Promise<void> {
    try {
      const result = await spawnCollect("git", ["-C", checkoutPath, "rev-parse", "--git-common-dir"], {
        cwd: checkoutPath,
        timeoutMs: 10_000,
        maxBuffer: 64 * 1024
      });
      const rawGitDir = result.stdout.trim();
      if (!rawGitDir) return;
      const excludePath = join(resolve(checkoutPath, rawGitDir), "info", "exclude");
      await mkdir(dirname(excludePath), { recursive: true });
      const current = (await pathExists(excludePath)) ? await readFile(excludePath, "utf8") : "";
      if (!current.split(/\r?\n/u).some((line) => line.trim() === "mempalace.yaml")) {
        await appendFile(excludePath, (current.endsWith("\n") || current.length === 0 ? "" : "\n") + "mempalace.yaml\n", "utf8");
      }
    } catch (error) {
      this.logger.debug({ error, checkoutPath }, "Could not add generated mempalace.yaml to git exclude");
    }
  }

  private ensureToken(): Promise<string> {
    if (this.remoteToken) return Promise.resolve(this.remoteToken);
    this.tokenPromise ??= this.createToken().catch((error: unknown) => {
      this.tokenPromise = null;
      throw error;
    });
    return this.tokenPromise;
  }

  private async createToken(): Promise<string> {
    const tokenFile = this.config.mempalaceRemoteTokenFile;
    await mkdir(dirname(tokenFile), { recursive: true });
    const entries = await readTokenEntries(tokenFile);
    const configuredToken = this.config.mempalaceRemoteToken?.trim();
    const existingToken = entries.find((entry) => entry.enabled !== false && typeof entry.token === "string")?.token;
    const token = configuredToken || (typeof existingToken === "string" ? existingToken : randomBytes(32).toString("base64url"));
    const withoutLocal = entries.filter((entry) => entry.name !== "actuarius-local");
    withoutLocal.unshift({ token, name: "actuarius-local", enabled: true });
    await writeFile(tokenFile, JSON.stringify(withoutLocal, null, 2) + "\n", "utf8");
    try {
      await chmod(tokenFile, 0o600);
    } catch {
      // chmod is best effort on non-Unix development hosts.
    }
    process.env.MEMPALACE_REMOTE_TOKEN = token;
    this.remoteToken = token;
    return token;
  }

  private async writeGlobalConfig(): Promise<void> {
    const write = this.writeConfigPromise.catch(() => undefined).then(() => this.writeGlobalConfigOnce());
    this.writeConfigPromise = write.catch(() => undefined);
    await write;
  }

  private async writeGlobalConfigOnce(): Promise<void> {
    await this.ensureToken();
    const configDir = join(this.homeDir, ".mempalace");
    const configPath = join(configDir, "config.json");
    await mkdir(configDir, { recursive: true });
    const current = await readJsonObject(configPath);

    const server = isRecord(current.server) ? { ...current.server } : {};
    const existingCheckouts = isRecord(server.checkouts) ? server.checkouts : {};
    const checkouts: Record<string, string> = { ...existingCheckouts } as Record<string, string>;
    for (const [wing, checkoutPath] of this.repoCheckouts.entries()) checkouts[wing] = checkoutPath;

    const federation = isRecord(current.federation) ? { ...current.federation } : {};
    const existingRemotes = Array.isArray(federation.remotes) ? federation.remotes.filter(isRecord) : [];
    const remotes = existingRemotes.filter((remote) => remote.name !== this.config.mempalaceRemoteName);
    remotes.push({
      name: this.config.mempalaceRemoteName,
      url: this.config.mempalaceRemoteUrl,
      token_env: "MEMPALACE_REMOTE_TOKEN",
      timeout_ms: this.config.mempalaceRemoteTimeoutMs
    });

    const existingWings = isRecord(federation.wings) ? federation.wings : {};
    const wings: Record<string, unknown> = { ...existingWings };
    for (const wing of this.repoCheckouts.keys()) {
      wings[wing] = { mode: "combined", remote: this.config.mempalaceRemoteName, write: "remote" };
    }

    const nextConfig = {
      ...current,
      version: 1,
      palace_path: this.config.mempalacePalacePath,
      server: {
        ...server,
        bind: this.config.mempalaceRemoteBind,
        token_file: this.config.mempalaceRemoteTokenFile,
        checkouts
      },
      federation: {
        ...federation,
        remotes,
        default_mode: typeof federation.default_mode === "string" ? federation.default_mode : "local",
        wings
      }
    };
    await writeFile(configPath, JSON.stringify(nextConfig, null, 2) + "\n", "utf8");
  }

  private buildProcessEnv(): NodeJS.ProcessEnv {
    return {
      ...process.env,
      MEMPALACE_REMOTE_TOKEN: this.remoteToken ?? process.env.MEMPALACE_REMOTE_TOKEN ?? "",
      MEMPALACE_EMBED_ALLOW_DOWNLOADS: "1"
    };
  }

  private async startServer(): Promise<void> {
    if (this.server) return;
    await mkdir(this.config.mempalaceRemotePalacePath, { recursive: true });
    const args = [
      "--palace",
      this.config.mempalaceRemotePalacePath,
      "serve",
      "--bind",
      this.config.mempalaceRemoteBind,
      "--token-file",
      this.config.mempalaceRemoteTokenFile
    ];

    this.expectedServerExit = false;
    this.server = spawn(this.config.mempalaceCliPath, args, { env: this.buildProcessEnv(), stdio: ["ignore", "pipe", "pipe"] });
    createInterface({ input: this.server.stdout! }).on("line", (line) => {
      if (this.expectedServerExit) return;
      this.logger.debug({ line }, "mempalace-cli serve stdout");
    });
    createInterface({ input: this.server.stderr! }).on("line", (line) => {
      if (this.expectedServerExit) return;
      this.logger.info({ line }, "mempalace-cli serve");
    });
    this.server.on("error", (error) => this.logger.error({ error }, "MemPalace federation server process error"));
    this.server.on("close", (code) => {
      const expected = this.expectedServerExit;
      this.server = null;
      if (!expected) this.logger.warn({ code }, "MemPalace federation server exited unexpectedly");
    });

    await this.waitForHealth();
    this.logger.info(
      { bind: this.config.mempalaceRemoteBind, url: this.config.mempalaceRemoteUrl, palacePath: this.config.mempalaceRemotePalacePath },
      "MemPalace federation server ready"
    );
  }

  private async stopServer(): Promise<void> {
    const child = this.server;
    if (!child) return;
    this.expectedServerExit = true;
    await new Promise<void>((resolveDone) => {
      const timer = setTimeout(() => {
        if (!child.killed) child.kill("SIGKILL");
        resolveDone();
      }, 5_000);
      child.once("close", () => {
        clearTimeout(timer);
        resolveDone();
      });
      child.kill("SIGTERM");
    });
    this.server = null;
  }

  private async restartServer(): Promise<void> {
    await this.stopServer();
    await this.startServer();
  }

  private async waitForHealth(): Promise<void> {
    const healthUrl = new URL("/v1/health", this.config.mempalaceRemoteUrl).toString();
    const deadline = Date.now() + 15_000;
    let lastError: unknown = null;
    while (Date.now() < deadline) {
      if (!this.server) throw new Error("MemPalace federation server exited before it became healthy");
      try {
        const response = await fetch(healthUrl, { signal: AbortSignal.timeout(2_000) });
        if (response.ok) return;
        lastError = new Error("health returned HTTP " + response.status);
      } catch (error) {
        lastError = error;
      }
      await new Promise((resolveDelay) => setTimeout(resolveDelay, 250));
    }
    throw new Error("MemPalace federation server did not become healthy: " + (lastError instanceof Error ? lastError.message : String(lastError)));
  }

  private async runMainBranchMine(repo: RepoMemoryIdentity, checkoutPath: string, wing: string): Promise<void> {
    const args = ["--palace", this.config.mempalacePalacePath, "mine", checkoutPath];
    if (this.config.mempalaceRemoteMineBatchSize > 0) args.push("--batch-size", String(this.config.mempalaceRemoteMineBatchSize));
    this.logger.info({ repo: repo.fullName, wing, checkoutPath }, "MemPalace remote mine queued");
    const result = await spawnCollect(this.config.mempalaceCliPath, args, {
      cwd: checkoutPath,
      env: this.buildProcessEnv(),
      timeoutMs: this.config.mempalaceRemoteMineTimeoutMs,
      maxBuffer: 4 * 1024 * 1024
    });
    this.logger.info({ repo: repo.fullName, wing, stdout: result.stdout.trim(), stderr: result.stderr.trim() }, "MemPalace remote mine completed");
  }
}
