export function buildHelpText(): string {
  return [
    "**Actuarius Commands**",
    "- `/help` Show this command list.",
    "- `/connect-repo repo:<owner/name>` Link a GitHub repo to this server and create its channel.",
    "- `/sync-repo [repo:<owner/name>]` Sync an existing connected repo checkout to `master`.",
    "- `/cleanup [repo:<owner/name>]` Delete local branches whose origin branches are gone. In a non-repo channel, cleans all connected repos after confirmation.",
    "- `/repos` List connected repos and their channels.",
    "- `/issues [mode:<list|summary|detail>] [issue:<number>]` Read open GitHub issues for the connected repo.",
    "- `/ask prompt:<text>` Create a new request thread and run AI in an isolated worktree.",
    "- `/plan prompt:<text> [iterative:true]` Create a request thread, run a planner, then run an implementer (with `iterative`, breaks into per-task implementation and verification).",
    "- `/install [package:<allowed-package-id>] [apt-package:<deb-specs>] scope:<repo|request>` Install an allowlisted tool or apt package (admin only; specify exactly one of `package` or `apt-package`).",
    "- `/review` Run adversarial code review on the current request worktree, including staged, unstaged, and untracked changes (request owner or Manage Server).",
    "- `/revise [findings:<text>]` Re-run planner-verified implementation on the current request thread. Findings can be provided explicitly or will be pulled from the latest review summary (request owner or Manage Server).",
    "- `/pr` Open a draft pull request for the current request thread after changes are committed and `/review` returns `ready_for_pr` for the current HEAD.",
    "- `/review-rounds [rounds:<number>]` Show or set the max `/review` consensus rounds for this server (admin only to set).",
    "- `/update-clis [provider:<claude|codex|gemini>]` Update provider CLIs to latest. Omit provider to update all (admin only).",
    "- `/model-select [provider:<claude|codex|gemini|opencode>] [model:<name>] [role:<default|planner|implementer|reviewer-1–reviewer-4|reviewer-analyzer|reviewer-judge|reviewer-summarizer>] [clear:true]` Set or clear provider/model roles (admin only).",
    "- `/model-current` Show the active AI provider and model for this server.",
    "- `/codex-auth credentials:<file>` Upload Codex credentials file from `~/.codex/auth.json` (admin only).",
    "- `/opencode-auth provider:<name> key:<your-key>` Configure an API key for OpenCode to use with a specific AI provider (admin only).",
    "- `/opencode-auth-remove provider:<name>` Remove a stored API key for OpenCode (admin only).",
    "",
    "v1 notes:",
    "- Private repos work when the configured GitHub identity can access them.",
    "- `/ask` uses queued AI execution with per-guild concurrency limits.",
    "- Codex and Gemini require `ENABLE_CODEX_EXECUTION` / `ENABLE_GEMINI_EXECUTION` to be enabled.",
    "- Gemini additionally requires `GEMINI_API_KEY`.",
    "- OpenCode requires `ENABLE_OPENCODE_EXECUTION` and API keys. Use `/opencode-auth` to configure per-provider keys (deepseek, openai, anthropic, etc.) or set the relevant env vars on the instance.",
    "- OpenCode supports any provider/model combination via `--model <provider>/<model>`, e.g. `deepseek/deepseek-v4-pro`, `openai/o4-mini`, `anthropic/claude-sonnet-4-6`."
  ].join("\n");
}
